[package]
name = "peek_iter"
version = "0.1.0"
authors = ["Dan Cojocaru <dancojocaru2010@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
