[package]
name = "kennsh_syscall_macro"
version = "0.1.0"
authors = ["Dan Cojocaru <dan.cojocaru00@e-uvt.ro>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.24"
syn = { version = "1.0.54", features = ["full"] }
